package com.hitachi.coe.fullstack.model;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.Date;

import org.junit.jupiter.api.Test;

public class SurveyDataModelUnitTest {

    @Test
    public void testModelSurveyData() {
    	SurveyDataModel surveyDataModel = new SurveyDataModel();
		Date dateTestDate = new Date();
		surveyDataModel.setId(1);
		surveyDataModel.setStartTime(dateTestDate);
		surveyDataModel.setCompletionTime(dateTestDate);
		surveyDataModel.setEmployeeId("1");
		surveyDataModel.setEmail("survey@gmail.com");
		surveyDataModel.setName("Nguyen Van A");
		surveyDataModel.setFullName("Nguyen Van B");
		surveyDataModel.setCurrentAddress("Ho Chi Minh" );
		surveyDataModel.setEnglish("English");
		surveyDataModel.setJapanese("Japan");
		surveyDataModel.setCertificate("Topic");
		surveyDataModel.setWaterfall(1 );
		surveyDataModel.setAgile(2 );
		surveyDataModel.setManufacturing("Manufacturing");
		surveyDataModel.setSemiconductor("Semiconductor");
		surveyDataModel.setTransportation("Transportation");
		surveyDataModel.setIotLumada("IotLumada");
		surveyDataModel.setEnergyUtilities("EnergyUtilities");
		surveyDataModel.setRetailLogistic("RetailLogistic");
		surveyDataModel.setAutomotive("Automotive");
		surveyDataModel.setFinanceBanking("FinanceBanking");
		surveyDataModel.setInsurance("Insurance");
		surveyDataModel.setHealthCare("HealthCare");
		surveyDataModel.setPrinting("Printing");
		surveyDataModel.setSmartSpace("SmartSpace");
		surveyDataModel.setOther("Others");
		surveyDataModel.setCPlus(3);
		surveyDataModel.setCSharp(4);
		surveyDataModel.setJava(5);
		surveyDataModel.setGolang(6);
		surveyDataModel.setKotlin(7);
		surveyDataModel.setPython(8);
		surveyDataModel.setR(9);
		surveyDataModel.setPhp(10);
		surveyDataModel.setVisualBasicDotNET(11);
		surveyDataModel.setVisualBasic6(12);
		surveyDataModel.setCssAndHtml(13);
		surveyDataModel.setJavascript(14);
		surveyDataModel.setBootstrapMaterial(15);
		surveyDataModel.setJQuery(16);
		surveyDataModel.setAngular(17);
		surveyDataModel.setAngularJs(18);
		surveyDataModel.setReact(19);
		surveyDataModel.setNestJs(20);
		surveyDataModel.setVueJs(21);
		surveyDataModel.setSencha(22);
		surveyDataModel.setReactNative(23);
		surveyDataModel.setPrism(24);
		surveyDataModel.setFlutter(25);
		surveyDataModel.setTypeScript(26);
		surveyDataModel.setJavaSpringBoot(27);
		surveyDataModel.setJavaSpringMvc(28);
		surveyDataModel.setJavaJsp(29);
		surveyDataModel.setJavaPlayFramework(30);
		surveyDataModel.setDotNetCore(31);
		surveyDataModel.setVbDotNet(32);
		surveyDataModel.setAspDotNet(33);
		surveyDataModel.setPythonFlask(34);
		surveyDataModel.setPythonDjango(35);
		surveyDataModel.setGo(36);
		surveyDataModel.setKotlinTwo(37);
		surveyDataModel.setQuarkus(38);
		surveyDataModel.setMicronaut(39);
		surveyDataModel.setNodeRed(40);
		surveyDataModel.setNodeJs(41);
		surveyDataModel.setOraclePlSql(42);
		surveyDataModel.setIotWebSocket(43);
		surveyDataModel.setIotThinkWorx(44);
		surveyDataModel.setIotMqtt(45);
		surveyDataModel.setDotNetWinForm(46);
		surveyDataModel.setDotNetWpf(47);
		surveyDataModel.setJavaSwing(48);
		surveyDataModel.setJavaFx(49);
		surveyDataModel.setOracleFormReport(50);
		surveyDataModel.setWebSphereApplicationServer(51);
		surveyDataModel.setJBossWildFly(52);
		surveyDataModel.setIis(53);
		surveyDataModel.setTomcat(54);
		surveyDataModel.setNetty(55);
		surveyDataModel.setMaven(56);
		surveyDataModel.setGradle(57);
		surveyDataModel.setOracleDb(59);
		surveyDataModel.setPostgreSql(59);
		surveyDataModel.setMySql(60);
		surveyDataModel.setMariaDb(61);
		surveyDataModel.setSqlServer(62);
		surveyDataModel.setDbTwo(63);
		surveyDataModel.setInfluxDb(64);
		surveyDataModel.setPrometheus(65);
		surveyDataModel.setDruid(66);
		surveyDataModel.setAzureTimeSeriesInsight(67);
		surveyDataModel.setAwsTimeStream(68);
		surveyDataModel.setMongoDb(69);
		surveyDataModel.setCassandra(70);
		surveyDataModel.setCouchbase(71);
		surveyDataModel.setNeoFourJ(72);
		surveyDataModel.setArangoDb(73);
		surveyDataModel.setCamunda(74);
		surveyDataModel.setWpsSoa(75);
		surveyDataModel.setMuleSoft(76);
		surveyDataModel.setCqrs(77);
		surveyDataModel.setSaga(78);
		surveyDataModel.setCircuitBreaker(79);
		surveyDataModel.setKong(80);
		surveyDataModel.setAwsApiGateway(81);
		surveyDataModel.setAzureApiManagement(82);
		surveyDataModel.setTyk(83);
		surveyDataModel.setWsoTwo(84);
		surveyDataModel.setApigee(85);
		surveyDataModel.setKeycloak(86);
		surveyDataModel.setOkta(87);
		surveyDataModel.setAzureAd(88);
		surveyDataModel.setAuthZero(89);
		surveyDataModel.setAwsIam(90);
		surveyDataModel.setApacheSpark(91);
		surveyDataModel.setApacheNifi(92);
		surveyDataModel.setRabbitMq(93);
		surveyDataModel.setKafka(94);
		surveyDataModel.setActiveMq(95);
		surveyDataModel.setMicrosoftBiztalk(96);
		surveyDataModel.setTibcoEms(97);
		surveyDataModel.setRedis(98);
		surveyDataModel.setMemcached(99);
		surveyDataModel.setApacheIgnite(100);
		surveyDataModel.setElasticSearch(101);
		surveyDataModel.setNginx(102);
		surveyDataModel.setHaProxy(103);
		surveyDataModel.setFundamentals(104);
		surveyDataModel.setCicdTools(105);
		surveyDataModel.setNetworking(106);
		surveyDataModel.setSecurityOne(107);
		surveyDataModel.setVirtualMachine(108);
		surveyDataModel.setBuildCompose(109);
		surveyDataModel.setDocker(110);
		surveyDataModel.setSonarQube(111);
		surveyDataModel.setKubernetes(112);
		surveyDataModel.setJenkins(113);
		surveyDataModel.setJira(114);
		surveyDataModel.setSvn(115);
		surveyDataModel.setGitLab(116);
		surveyDataModel.setGitHub(117);
		surveyDataModel.setBitbucket(118);
		surveyDataModel.setAzureRepos(119);
		surveyDataModel.setAwsCodeCommit(120);
		surveyDataModel.setTableau(121);
		surveyDataModel.setPowerBi(122);
		surveyDataModel.setPentaho(123);
		surveyDataModel.setQlikView(124);
		surveyDataModel.setGoogleDataStudio(125);
		surveyDataModel.setIbmCognos(126);
		surveyDataModel.setQlikSense(127);
		surveyDataModel.setAws(128);
		surveyDataModel.setUiAutomation(129);
		surveyDataModel.setAzure(130);
		surveyDataModel.setApi(131);
		surveyDataModel.setPerformance(132);
		surveyDataModel.setGcp(133);
		surveyDataModel.setSecurityTwo(134);
		surveyDataModel.setCouldStack(135);
		surveyDataModel.setOpenStack(136);
		surveyDataModel.setLocalStack(137);
		surveyDataModel.setPcf(138);
		surveyDataModel.setSaleForce(139);
		surveyDataModel.setOci(140);
		surveyDataModel.setAnsible(141);
		surveyDataModel.setTerraform(142);
		surveyDataModel.setAdobeFigma(143);
		surveyDataModel.setAdobeXd(144);
		surveyDataModel.setInVision(145);
		surveyDataModel.setSketch(146);
		surveyDataModel.setFlinto(147);
		surveyDataModel.setFramer(148);
		surveyDataModel.setUxPin(149);
		surveyDataModel.setWireFrameBalsamiq(150);
		surveyDataModel.setMotionDesign(151);
		surveyDataModel.setAdobePhotoshop(152);
		surveyDataModel.setAdobeIllustrator(153);
		surveyDataModel.setAdobeExpress(154);
		surveyDataModel.setAdobeInDesign(155);
		surveyDataModel.setAdobePremierePro(156);
		surveyDataModel.setAdobeAfterEffects(157);
		surveyDataModel.setAdobeAudition(158);
		surveyDataModel.setAdobeAnimate(159);
		surveyDataModel.setMaterialDesign(160);
		surveyDataModel.setAppleHumanInterfaceGuidelines(161);
		surveyDataModel.setMuiTheme(162);
		surveyDataModel.setHitachiNextTheme(163);
		surveyDataModel.setW3c(164);
		surveyDataModel.setCsunAccessibility(165);
		surveyDataModel.setUxResearcher(166);
		surveyDataModel.setUxWriting(167);
		surveyDataModel.setAngularStyleTheme(168);
		surveyDataModel.setReactStyleTheme(169);
		surveyDataModel.setWpfStyleTheme(170);
		surveyDataModel.setSassCss(171);
		surveyDataModel.setLessCss(172);
		surveyDataModel.setListOtherSkills("OtherSkills");

		assertEquals(1, surveyDataModel.getId());
		assertEquals(dateTestDate, surveyDataModel.getStartTime());
		assertEquals(dateTestDate, surveyDataModel.getCompletionTime());
		assertEquals("survey@gmail.com", surveyDataModel.getEmail());
		assertEquals("Nguyen Van A", surveyDataModel.getName());
		assertEquals("1", surveyDataModel.getEmployeeId());
		assertEquals("Nguyen Van B", surveyDataModel.getFullName());
		assertEquals("Ho Chi Minh", surveyDataModel.getCurrentAddress());
		assertEquals("English", surveyDataModel.getEnglish());
		assertEquals("Japan", surveyDataModel.getJapanese());
		assertEquals("Topic", surveyDataModel.getCertificate());
		assertEquals(1, surveyDataModel.getWaterfall());
		assertEquals(2, surveyDataModel.getAgile());
		assertEquals("Manufacturing", surveyDataModel.getManufacturing());
		assertEquals("Semiconductor", surveyDataModel.getSemiconductor());
		assertEquals("Transportation", surveyDataModel.getTransportation());
		assertEquals("IotLumada", surveyDataModel.getIotLumada());
		assertEquals("EnergyUtilities", surveyDataModel.getEnergyUtilities());
		assertEquals("RetailLogistic", surveyDataModel.getRetailLogistic());
		assertEquals("Automotive", surveyDataModel.getAutomotive());
		assertEquals("FinanceBanking", surveyDataModel.getFinanceBanking());
		assertEquals("Insurance", surveyDataModel.getInsurance());
		assertEquals("HealthCare", surveyDataModel.getHealthCare());
		assertEquals("Printing", surveyDataModel.getPrinting());
		assertEquals("SmartSpace", surveyDataModel.getSmartSpace());
		assertEquals("Others", surveyDataModel.getOther());
		assertEquals(3, surveyDataModel.getCPlus());
		assertEquals(4, surveyDataModel.getCSharp());
		assertEquals(5, surveyDataModel.getJava());
		assertEquals(6, surveyDataModel.getGolang());
		assertEquals(7, surveyDataModel.getKotlin());
		assertEquals(8, surveyDataModel.getPython());
		assertEquals(9, surveyDataModel.getR());
		assertEquals(10, surveyDataModel.getPhp());
		assertEquals(11, surveyDataModel.getVisualBasicDotNET());
		assertEquals(12, surveyDataModel.getVisualBasic6());
		assertEquals(13, surveyDataModel.getCssAndHtml());
		assertEquals(14, surveyDataModel.getJavascript());
		assertEquals(15, surveyDataModel.getBootstrapMaterial());
		assertEquals(16, surveyDataModel.getJQuery());
		assertEquals(17, surveyDataModel.getAngular());
		assertEquals(18, surveyDataModel.getAngularJs());
		assertEquals(19, surveyDataModel.getReact());
		assertEquals(20, surveyDataModel.getNestJs());
		assertEquals(21, surveyDataModel.getVueJs());
		assertEquals(22, surveyDataModel.getSencha());
		assertEquals(23, surveyDataModel.getReactNative());
		assertEquals(24, surveyDataModel.getPrism());
		assertEquals(25, surveyDataModel.getFlutter());
		assertEquals(26, surveyDataModel.getTypeScript());
		assertEquals(27, surveyDataModel.getJavaSpringBoot());
		assertEquals(28, surveyDataModel.getJavaSpringMvc());
		assertEquals(29, surveyDataModel.getJavaJsp());
		assertEquals(30, surveyDataModel.getJavaPlayFramework());
		assertEquals(31, surveyDataModel.getDotNetCore());
		assertEquals(32, surveyDataModel.getVbDotNet());
		assertEquals(33, surveyDataModel.getAspDotNet());
		assertEquals(34, surveyDataModel.getPythonFlask());
		assertEquals(35, surveyDataModel.getPythonDjango());
		assertEquals(36, surveyDataModel.getGo());
		assertEquals(37, surveyDataModel.getKotlinTwo());
		assertEquals(38, surveyDataModel.getQuarkus());
		assertEquals(39, surveyDataModel.getMicronaut());
		assertEquals(40, surveyDataModel.getNodeRed());
		assertEquals(41, surveyDataModel.getNodeJs());
		assertEquals(42, surveyDataModel.getOraclePlSql());
		assertEquals(43, surveyDataModel.getIotWebSocket());
		assertEquals(44, surveyDataModel.getIotThinkWorx());
		assertEquals(45, surveyDataModel.getIotMqtt());
		assertEquals(46, surveyDataModel.getDotNetWinForm());
		assertEquals(47, surveyDataModel.getDotNetWpf());
		assertEquals(48, surveyDataModel.getJavaSwing());
		assertEquals(49, surveyDataModel.getJavaFx());
		assertEquals(50, surveyDataModel.getOracleFormReport());
		assertEquals(51, surveyDataModel.getWebSphereApplicationServer());
		assertEquals(52, surveyDataModel.getJBossWildFly());
		assertEquals(53, surveyDataModel.getIis());
		assertEquals(54, surveyDataModel.getTomcat());
		assertEquals(55, surveyDataModel.getNetty());
		assertEquals(56, surveyDataModel.getMaven());
		assertEquals(57, surveyDataModel.getGradle());
		assertEquals(59, surveyDataModel.getOracleDb());
		assertEquals(59, surveyDataModel.getPostgreSql());
		assertEquals(60, surveyDataModel.getMySql());
		assertEquals(61, surveyDataModel.getMariaDb());
		assertEquals(62, surveyDataModel.getSqlServer());
		assertEquals(63, surveyDataModel.getDbTwo());
		assertEquals(64, surveyDataModel.getInfluxDb());
		assertEquals(65, surveyDataModel.getPrometheus());
		assertEquals(66, surveyDataModel.getDruid());
		assertEquals(67, surveyDataModel.getAzureTimeSeriesInsight());
		assertEquals(68, surveyDataModel.getAwsTimeStream());
		assertEquals(69, surveyDataModel.getMongoDb());
		assertEquals(70, surveyDataModel.getCassandra());
		assertEquals(71, surveyDataModel.getCouchbase());
		assertEquals(72, surveyDataModel.getNeoFourJ());
		assertEquals(73, surveyDataModel.getArangoDb());
		assertEquals(74, surveyDataModel.getCamunda());
		assertEquals(75, surveyDataModel.getWpsSoa());
		assertEquals(76, surveyDataModel.getMuleSoft());
		assertEquals(77, surveyDataModel.getCqrs());
		assertEquals(78, surveyDataModel.getSaga());
		assertEquals(79, surveyDataModel.getCircuitBreaker());
		assertEquals(80, surveyDataModel.getKong());
		assertEquals(81, surveyDataModel.getAwsApiGateway());
		assertEquals(82, surveyDataModel.getAzureApiManagement());
		assertEquals(83, surveyDataModel.getTyk());
		assertEquals(84, surveyDataModel.getWsoTwo());
		assertEquals(85, surveyDataModel.getApigee());
		assertEquals(86, surveyDataModel.getKeycloak());
		assertEquals(87, surveyDataModel.getOkta());
		assertEquals(88, surveyDataModel.getAzureAd());
		assertEquals(89, surveyDataModel.getAuthZero());
		assertEquals(90, surveyDataModel.getAwsIam());
		assertEquals(91, surveyDataModel.getApacheSpark());
		assertEquals(92, surveyDataModel.getApacheNifi());
		assertEquals(93, surveyDataModel.getRabbitMq());
		assertEquals(94, surveyDataModel.getKafka());
		assertEquals(95, surveyDataModel.getActiveMq());
		assertEquals(96, surveyDataModel.getMicrosoftBiztalk());
		assertEquals(97, surveyDataModel.getTibcoEms());
		assertEquals(98, surveyDataModel.getRedis());
		assertEquals(99, surveyDataModel.getMemcached());
		assertEquals(100, surveyDataModel.getApacheIgnite());
		assertEquals(101, surveyDataModel.getElasticSearch());
		assertEquals(102, surveyDataModel.getNginx());
		assertEquals(103, surveyDataModel.getHaProxy());
		assertEquals(104, surveyDataModel.getFundamentals());
		assertEquals(105, surveyDataModel.getCicdTools());
		assertEquals(106, surveyDataModel.getNetworking());
		assertEquals(107, surveyDataModel.getSecurityOne());
		assertEquals(108, surveyDataModel.getVirtualMachine());
		assertEquals(109, surveyDataModel.getBuildCompose());
		assertEquals(110, surveyDataModel.getDocker());
		assertEquals(111, surveyDataModel.getSonarQube());
		assertEquals(112, surveyDataModel.getKubernetes());
		assertEquals(113, surveyDataModel.getJenkins());
		assertEquals(114, surveyDataModel.getJira());
		assertEquals(115, surveyDataModel.getSvn());
		assertEquals(116, surveyDataModel.getGitLab());
		assertEquals(117, surveyDataModel.getGitHub());
		assertEquals(118, surveyDataModel.getBitbucket());
		assertEquals(119, surveyDataModel.getAzureRepos());
		assertEquals(120, surveyDataModel.getAwsCodeCommit());
		assertEquals(121, surveyDataModel.getTableau());
		assertEquals(122, surveyDataModel.getPowerBi());
		assertEquals(123, surveyDataModel.getPentaho());
		assertEquals(124, surveyDataModel.getQlikView());
		assertEquals(125, surveyDataModel.getGoogleDataStudio());
		assertEquals(126, surveyDataModel.getIbmCognos());
		assertEquals(127, surveyDataModel.getQlikSense());
		assertEquals(128, surveyDataModel.getAws());
		assertEquals(129, surveyDataModel.getUiAutomation());
		assertEquals(130, surveyDataModel.getAzure());
		assertEquals(131, surveyDataModel.getApi());
		assertEquals(132, surveyDataModel.getPerformance());
		assertEquals(133, surveyDataModel.getGcp());
		assertEquals(134, surveyDataModel.getSecurityTwo());
		assertEquals(135, surveyDataModel.getCouldStack());
		assertEquals(136, surveyDataModel.getOpenStack());
		assertEquals(137, surveyDataModel.getLocalStack());
		assertEquals(138, surveyDataModel.getPcf()); 
		assertEquals(139, surveyDataModel.getSaleForce());
		assertEquals(140, surveyDataModel.getOci());
		assertEquals(141, surveyDataModel.getAnsible());
		assertEquals(142, surveyDataModel.getTerraform());
		assertEquals(143, surveyDataModel.getAdobeFigma());
		assertEquals(144, surveyDataModel.getAdobeXd());
		assertEquals(145, surveyDataModel.getInVision());
		assertEquals(146, surveyDataModel.getSketch());
		assertEquals(147, surveyDataModel.getFlinto());
		assertEquals(148, surveyDataModel.getFramer());
		assertEquals(149, surveyDataModel.getUxPin());
		assertEquals(150, surveyDataModel.getWireFrameBalsamiq());
		assertEquals(151, surveyDataModel.getMotionDesign());
		assertEquals(152, surveyDataModel.getAdobePhotoshop());
		assertEquals(153, surveyDataModel.getAdobeIllustrator());
		assertEquals(154, surveyDataModel.getAdobeExpress());
		assertEquals(155, surveyDataModel.getAdobeInDesign());
		assertEquals(156, surveyDataModel.getAdobePremierePro());
		assertEquals(157, surveyDataModel.getAdobeAfterEffects());
		assertEquals(158, surveyDataModel.getAdobeAudition());
		assertEquals(159, surveyDataModel.getAdobeAnimate());
		assertEquals(160, surveyDataModel.getMaterialDesign());
		assertEquals(161, surveyDataModel.getAppleHumanInterfaceGuidelines());
		assertEquals(162, surveyDataModel.getMuiTheme());
		assertEquals(163, surveyDataModel.getHitachiNextTheme());
		assertEquals(164, surveyDataModel.getW3c());
		assertEquals(165, surveyDataModel.getCsunAccessibility());
		assertEquals(166, surveyDataModel.getUxResearcher());
		assertEquals(167, surveyDataModel.getUxWriting());
		assertEquals(168, surveyDataModel.getAngularStyleTheme());
		assertEquals(169, surveyDataModel.getReactStyleTheme());
		assertEquals(170, surveyDataModel.getWpfStyleTheme());
		assertEquals(171, surveyDataModel.getSassCss());
		assertEquals(172, surveyDataModel.getLessCss());
		assertEquals("OtherSkills", surveyDataModel.getListOtherSkills());
    }
}
