INSERT INTO public.skill_set(id, code, name, description, created_by, created_date) VALUES
(1, 'C#', 'C#', 'A modern, general-purpose programming language', 'master', now()),
(2, 'Java', 'Java', 'Object-oriented programming language', 'master', now()),
(3, 'Golang', 'Golang', 'A statically typed, compiled programming language', 'master', now()),
(4, 'Kotlin', 'Kotlin', 'Across-platform programming language', 'master', now()),
(5, 'Python', 'Python', 'A high-level, interpreted programming language', 'master', now()),
(6, 'R', 'R', 'A programming language graphics', 'master', now()),
(7, 'PHP', 'PHP', 'A language designed for web development', 'master', now()),
(8, 'VB.NET', 'Visual Basic.NET', 'An object-oriented programming language', 'master', now()),
(9, 'VB6', 'Visual Basic 6', 'An event-driven programming language', 'master', now()),
(10, 'HTML5', 'CSS & HTML5', 'A markup language used for creating web pages', 'master', now()),
(11, 'JS-BT/Mat', 'Bootstrap/Material', 'CSS framework for responsive web design', 'master', now()),
(12, 'JS-JQuery', 'JQuery', 'Fast and concise JavaScript library', 'master', now()),
(13, 'JS-Angular', 'Angular', 'TypeScript-based web app framework', 'master', now()),
(14, 'JS-AngularJS', 'AngularJS', 'JavaScript-based web app framework', 'master', now()),
(15, 'JS-React', 'React', 'Declarative JavaScript library', 'master', now()),
(16, 'JS-NestJS', 'NestJS', 'Node.js framework for building scalable apps', 'master', now()),
(17, 'JS-VueJS', 'VueJS', 'Progressive framework for building user interfaces', 'master', now()),
(18, 'JS-Sencha', 'Sencha', 'Web app dev platform for cross-platform apps', 'master', now()),
(19, 'JS-React Native', 'React Native', 'Build native mobile apps using JS', 'master', now()),
(20, 'JS-Next.js', 'Next.js', 'React-based framework for server-side rendering', 'master', now()),
(21, 'PR-Prism', 'Prism', 'Framework for building XAML-based apps','master',now()),
(22, 'FL-Flutter', 'Flutter', 'UI toolkit for building natively compiled apps','master',now()),
(23, 'TS-TypeScript', 'TypeScript', 'Typed superset of JavaScript','master',now()),
(24, 'JV-Spring Boot', 'Spring Boot', 'Java-based framework for web apps','master',now()),
(25, 'JV-Spring MVC', 'Spring MVC', 'Java-based framework for web apps','master',now()),
(26, 'JV-JSP', 'JSP', 'Java-based technology for dynamic web pages','master',now()),
(27, 'JV-Play Framework', 'Play Framework', 'Java- and Scala-based web app framework','master',now()),
(28, 'NC-.NET Core', '.NET Core', 'Cross-platform framework for building web apps','master',now()),
(29, 'VB-VB.NET', 'VB.NET', 'Object-oriented programming language for web apps','master',now()),
(30, 'AN-ASP.NET', 'ASP.NET', 'Web app framework for building dynamic web pages','master',now()),
(31, 'PY-Django', 'Django', 'Python-based web framework','master',now()),
(32, 'GO-Go', 'Go', 'Open-source programming language','master',now()),
(33, 'KT-Kotlin', 'Kotlin', 'Cross-platform language for mobile dev','master',now()),
(34, 'QR-Quarkus', 'Quarkus', 'Java-based cloud-native framework','master',now()),
(35, 'MN-Micronaut', 'Micronaut', 'Lightweight Java-based framework','master',now()),
(36, 'NR-NodeRED', 'NodeRED', 'Flow-based programming for IoT','master',now()),
(37, 'NS-NodeJS', 'NodeJS', 'JavaScript runtime for server-side dev','master',now()),
(38, 'OR-PL/SQL', 'Oracle PL/SQL', 'Procedural language for Oracle DB','master',now()),
(39, 'IOT-WebSocket', 'WebSocket', 'Protocol for real-time comm in IoT','master',now()),
(40, 'IOT-ThinkWorx', 'ThingWorx', 'Platform for industrial IoT apps','master',now()),
(41, 'IOT-MQTT', 'MQTT', 'Lightweight protocol for IoT data exchange','master',now()),
(42, 'NC-Winform', '.NET Winform', 'Desktop app dev with C#/.NET','master',now()),
(43, 'NC-WPF', '.NET WPF', 'Desktop app dev with XAML/.NET','master',now()),
(44, 'JV-Swing', 'Java Swing', 'Java-based GUI toolkit','master',now()),
(45, 'JV-JavaFX', 'JavaFX', 'Java-based framework for rich UIs','master',now()),
(46, 'OR-Form/Report', 'Oracle Form/Report', 'Tools for building DB apps','master',now()),
(47, 'WAS-Websphere', 'WebSphere', 'Java-based app server from IBM','master',now()),
(48, 'JB-Wildfly', 'Wildfly', 'Java-based app server from Red Hat','master',now()),
(49, 'II-IIS', 'IIS', 'Web server for Windows','master',now()),
(50, 'TC-Tomcat', 'Tomcat', 'Java-based web server from Apache','master',now()),
(51, 'JA-Netty', 'Netty', 'Java-based networking framework','master',now()),
(52, 'MV-Maven', 'Maven', 'Build and dependency management tool','master',now()),
(53, 'GR-Gradle', 'Gradle', 'Build and dependency management tool','master',now()),
(54, 'OR-DB', 'Oracle DB', 'Relational database management system','master',now()),
(55, 'PG-PostgreSQL', 'PostgreSQL', 'Open-source relational DBMS','master',now()),
(56, 'MY-MySQL', 'MySQL', 'Open-source relational DBMS','master',now()),
(57, 'MD-MariaDB', 'MariaDB', 'Open-source relational DBMS','master',now()),
(58, 'MS-SQL Server', 'SQL Server', 'Relational DBMS from Microsoft','master',now()),
(59, 'DB-DB2', 'DB2', 'Relational DBMS from IBM','master',now()),
(60, 'DB-InfluxDB', 'InfluxDB', 'Time-series DB for metrics and events','master',now()),
(61, 'PM-Prometheus', 'Prometheus', 'Open-source monitoring system','master',now()),
(62, 'DR-Druid', 'Druid', 'Column-oriented distributed data store','master',now()),
(63, 'AZ-TSI', 'Azure Time Series Insight', 'Azure-based time-series data analysis','master',now()),
(64, 'AWS-Timestream', 'AWS Timestream', 'AWS-based time-series data analysis','master',now()),
(65, 'MG-MongoDB', 'MongoDB', 'NoSQL document-oriented DBMS','master',now()),
(66, 'CA-Cassandra', 'Cassandra', 'Distributed NoSQL DBMS','master',now()),
(67, 'CB-Couchbase', 'Couchbase', 'NoSQL document-oriented DBMS','master',now()),
(68, 'N4-Neo4J', 'Neo4J', 'Graph DBMS for connected data','master',now()),
(69, 'AG-ArangoDB', 'ArangoDB', 'Multi-model DBMS for graph, doc, and KV','master',now()),
(70, 'CM-Camunda', 'Camunda', 'Platform for BPMN workflows','master',now()),
(71, 'WPS-SOA', 'WebSphere SOA', 'IBM suite for SOA architecture','master',now()),
(72, 'MS-Mulesoft', 'Mulesoft', 'API integration and management platform','master',now()),
(73, 'CQRS', 'CQRS', 'Command Query Responsibility Segregation pattern','master',now()),
(74, 'Saga', 'Saga', 'Pattern for handling long-lived transactions','master',now()),
(75, 'CB-Circuit Breaker', 'Circuit Breaker', 'Pattern for fault tolerance','master',now()),
(76, 'KG-Kong', 'Kong', 'Open-source API gateway and management','master',now()),
(77, 'AWS-API Gateway', 'AWS API Gateway', 'AWS-based API management','master',now()),
(78, 'AZ-API Management', 'Azure API Management', 'Azure-based API management','master',now()),
(79, 'TY-Tyk', 'Tyk', 'Open-source API gateway and management','master',now()),
(80, 'WSO2', 'WSO2', 'Open-source integration platform','master',now()),
(81, 'Apigee', 'Apigee', 'API gateway and management platform','master',now()),
(82, 'Keycloak', 'Keycloak', 'Open-source identity and access management','master',now()),
(83, 'Okta', 'Okta', 'Identity and access management platform','master',now()),
(84, 'AZ-AD', 'Azure AD', 'Cloud-based identity and access management','master',now()),
(85, 'Auth0', 'Auth0', 'Identity and access management platform','master',now()),
(86, 'AWS-IAM', 'AWS IAM', 'AWS-based identity and access management','master',now()),
(87, 'Apache Spark', 'Spark', 'Open-source data processing engine','master',now()),
(88, 'Apache Nifi', 'Nifi', 'Open-source data integration platform','master',now()),
(89, 'RabbitMQ', 'RabbitMQ', 'Open-source message broker','master',now()),
(90, 'Kafka', 'Kafka', 'Distributed streaming platform','master',now()),
(91, 'ActiveMQ', 'ActiveMQ', 'Open-source message broker','master',now()),
(92, 'MS-Biztalk', 'Biztalk', 'Microsoft integration platform','master',now()),
(93, 'Tibco EMS', 'Tibco EMS', 'Enterprise messaging system','master',now()),
(94, 'Redis', 'Redis', 'In-memory data structure store','master',now()),
(95, 'Memcached', 'Memcached', 'Distributed memory object caching','master',now()),
(96, 'Apache Ignite', 'Ignite', 'Distributed in-memory computing platform','master',now()),
(97, 'Elasticsearch', 'Elasticsearch', 'Open-source search and analytics engine','master',now()),
(98, 'NGINX', 'NGINX', 'Open-source web server and reverse proxy','master',now()),
(99, 'HAProxy', 'HAProxy', 'Open-source load balancer and proxy','master',now()),
(100, 'Fundamentals', 'Fundamentals', 'Operating system, scripting, Linux services, etc.','master',now())