INSERT INTO public."group"(id, code, name, created_by, created_date)
VALUES
(1, 'AD', 'admin', 'master', now());

INSERT INTO public."user"("name", email, "password", group_id, created_by, created_date)
VALUES
-- username: administrator
-- password: 1231231231221qQ!
('administrator', 'administrator@gmail.com', '$2a$10$VlBAZW1OHhCpvRVaIv/vb.GChbXLgH0RD0tL5UkBFtZeTg3J5MYZq', 1, 'master', now());

INSERT INTO public."right"(id, code, module, created_by, created_date)
VALUES
-------------------full rights
(1, 'GET', '/**', 'master', now()),
(2, 'POST', '/**', 'master', now()),
(3, 'PUT', '/**', 'master', now()),
(4, 'DELETE', '/**', 'master', now()),

-------------------full rights only v1
(5, 'GET', '/api/v1/**', 'master', now()),
(6, 'POST', '/api/v1/**', 'master', now()),
(7, 'PUT', '/api/v1/**', 'master', now()),
(8, 'DELETE', '/api/v1/**', 'master', now()),

-------------------full rights only v2
(9, 'GET', '/api/v2/**', 'master', now()),
(10, 'POST', '/api/v2/**', 'master', now()),
(11, 'PUT', '/api/v2/**', 'master', now()),
(12, 'DELETE', '/api/v2/**', 'master', now()),

-------------------branch
(13, 'GET', '/api/v1/branch/**', 'master', now()),
(14, 'POST', '/api/v1/branch/**', 'master', now()),
(15, 'PUT', '/api/v1/branch/**', 'master', now()),
(16, 'DELETE', '/api/v1/branch/**', 'master', now()),
(17, 'GET', '/api/v1/branches/**', 'master', now()),
(18, 'POST', '/api/v1/branches/**', 'master', now()),
(19, 'PUT', '/api/v1/branches/**', 'master', now()),
(20, 'DELETE', '/api/v1/branches/**', 'master', now()),

(21, 'GET', '/api/v2/branch/**', 'master', now()),
(22, 'POST', '/api/v2/branch/**', 'master', now()),
(23, 'PUT', '/api/v2/branch/**', 'master', now()),
(24, 'DELETE', '/api/v2/branch/**', 'master', now()),
(25, 'GET', '/api/v2/branches/**', 'master', now()),
(26, 'POST', '/api/v2/branches/**', 'master', now()),
(27, 'PUT', '/api/v2/branches/**', 'master', now()),
(28, 'DELETE', '/api/v2/branches/**', 'master', now()),

(29, 'PUT', '/api/v1/branch/update', 'master', now()),
(30, 'POST', '/api/v1/branch/create', 'master', now()),
(31, 'GET', '/api/v1/branch/get-branches', 'master', now()),
(32, 'GET', '/api/v1/branch/get-by-location/{locationId}', 'master', now()),

-------------------business-domain
(33, 'GET', '/api/v1/business-domain/**', 'master', now()),
(34, 'POST', '/api/v1/business-domain/**', 'master', now()),
(35, 'PUT', '/api/v1/business-domain/**', 'master', now()),
(36, 'DELETE', '/api/v1/business-domain/**', 'master', now()),
(37, 'GET', '/api/v1/business-domains/**', 'master', now()),
(38, 'POST', '/api/v1/business-domains/**', 'master', now()),
(39, 'PUT', '/api/v1/business-domains/**', 'master', now()),
(40, 'DELETE', '/api/v1/business-domains/**', 'master', now()),

(41, 'GET', '/api/v2/business-domain/**', 'master', now()),
(42, 'POST', '/api/v2/business-domain/**', 'master', now()),
(43, 'PUT', '/api/v2/business-domain/**', 'master', now()),
(44, 'DELETE', '/api/v2/business-domain/**', 'master', now()),
(45, 'GET', '/api/v2/business-domains/**', 'master', now()),
(46, 'POST', '/api/v2/business-domains/**', 'master', now()),
(47, 'PUT', '/api/v2/business-domains/**', 'master', now()),
(48, 'DELETE', '/api/v2/business-domains/**', 'master', now()),

(49, 'GET', '/api/v1/business-domain', 'master', now()),
(50, 'GET', '/api/v1/business-domain-by-practice/{practiceId}', 'master', now()),
(51, 'GET', '/api/v1/get-all-business-domain', 'master', now()),

-------------------business-unit
(52, 'GET', '/api/v1/business-unit/**', 'master', now()),
(53, 'POST', '/api/v1/business-unit/**', 'master', now()),
(54, 'PUT', '/api/v1/business-unit/**', 'master', now()),
(55, 'DELETE', '/api/v1/business-unit/**', 'master', now()),
(56, 'GET', '/api/v1/business-units/**', 'master', now()),
(57, 'POST', '/api/v1/business-units/**', 'master', now()),
(58, 'PUT', '/api/v1/business-units/**', 'master', now()),
(59, 'DELETE', '/api/v1/business-units/**', 'master', now()),

(60, 'GET', '/api/v2/business-unit/**', 'master', now()),
(61, 'POST', '/api/v2/business-unit/**', 'master', now()),
(62, 'PUT', '/api/v2/business-unit/**', 'master', now()),
(63, 'DELETE', '/api/v2/business-unit/**', 'master', now()),
(64, 'GET', '/api/v2/business-units/**', 'master', now()),
(65, 'POST', '/api/v2/business-units/**', 'master', now()),
(66, 'PUT', '/api/v2/business-units/**', 'master', now()),
(67, 'DELETE', '/api/v2/business-units/**', 'master', now()),

(68, 'POST', '/api/v1/business-unit/create', 'master', now()),
(69, 'PUT', '/api/v1/business-unit/update', 'master', now()),
(70, 'GET', '/api/v1/business-unit', 'master', now()),

-------------------center-of-excellence
(71, 'GET', '/api/v1/center-of-excellence/**', 'master', now()),
(72, 'POST', '/api/v1/center-of-excellence/**', 'master', now()),
(73, 'PUT', '/api/v1/center-of-excellence/**', 'master', now()),
(74, 'DELETE', '/api/v1/center-of-excellence/**', 'master', now()),
(75, 'GET', '/api/v1/center-of-excellences/**', 'master', now()),
(76, 'POST', '/api/v1/center-of-excellences/**', 'master', now()),
(77, 'PUT', '/api/v1/center-of-excellences/**', 'master', now()),
(78, 'DELETE', '/api/v1/center-of-excellences/**', 'master', now()),

(79, 'GET', '/api/v2/center-of-excellence/**', 'master', now()),
(80, 'POST', '/api/v2/center-of-excellence/**', 'master', now()),
(81, 'PUT', '/api/v2/center-of-excellence/**', 'master', now()),
(82, 'DELETE', '/api/v2/center-of-excellence/**', 'master', now()),
(83, 'GET', '/api/v2/center-of-excellences/**', 'master', now()),
(84, 'POST', '/api/v2/center-of-excellences/**', 'master', now()),
(85, 'PUT', '/api/v2/center-of-excellences/**', 'master', now()),
(86, 'DELETE', '/api/v2/center-of-excellences/**', 'master', now()),

(87, 'GET', '/api/v1/coe-core-team/list-coe', 'master', now()),

-------------------coe-core-team
(88, 'GET', '/api/v1/coe-core-team/**', 'master', NOW()),
(89, 'POST', '/api/v1/coe-core-team/**', 'master', NOW()),
(90, 'PUT', '/api/v1/coe-core-team/**', 'master', NOW()),
(91, 'DELETE', '/api/v1/coe-core-team/**', 'master', NOW()),
(92, 'GET', '/api/v1/coe-core-teams/**', 'master', NOW()),
(93, 'POST', '/api/v1/coe-core-teams/**', 'master', NOW()),
(94, 'PUT', '/api/v1/coe-core-teams/**', 'master', NOW()),
(95, 'DELETE', '/api/v1/coe-core-teams/**', 'master', NOW()),

(96, 'GET', '/api/v2/coe-core-team/**', 'master', NOW()),
(97, 'POST', '/api/v2/coe-core-team/**', 'master', NOW()),
(98, 'PUT', '/api/v2/coe-core-team/**', 'master', NOW()),
(99, 'DELETE', '/api/v2/coe-core-team/**', 'master', NOW()),
(100, 'GET', '/api/v2/coe-core-teams/**', 'master', NOW()),
(101, 'POST', '/api/v2/coe-core-teams/**', 'master', NOW()),
(102, 'PUT', '/api/v2/coe-core-teams/**', 'master', NOW()),
(103, 'DELETE', '/api/v2/coe-core-teams/**', 'master', NOW()),

(104, 'POST', '/api/v1/coe-core-team/create', 'master', NOW()),
(105, 'PUT', '/api/v1/coe-core-team/update', 'master', NOW()),
(106, 'PUT', '/api/v1/coe-core-team/add-members/{coeCoreTeamId}', 'master', NOW()),
(107, 'PUT', '/api/v1/coe-core-team/remove-members', 'master', NOW()),
(108, 'DELETE', '/api/v1/coe-core-team/delete/{id}', 'master', NOW()),
(109, 'GET', '/api/v1/coe-core-team/list-coe-team/{coeId}', 'master', NOW()),
(110, 'GET', '/api/v1/coe-core-team/list-coe-team', 'master', NOW()),

-------------------coe-utilization
(111, 'GET', '/api/v1/coe-utilization/**', 'master', NOW()),
(112, 'POST', '/api/v1/coe-utilization/**', 'master', NOW()),
(113, 'PUT', '/api/v1/coe-utilization/**', 'master', NOW()),
(114, 'DELETE', '/api/v1/coe-utilization/**', 'master', NOW()),
(115, 'GET', '/api/v1/coe-utilizations/**', 'master', NOW()),
(116, 'POST', '/api/v1/coe-utilizations/**', 'master', NOW()),
(117, 'PUT', '/api/v1/coe-utilizations/**', 'master', NOW()),
(118, 'DELETE', '/api/v1/coe-utilizations/**', 'master', NOW()),

(119, 'GET', '/api/v2/coe-utilization/**', 'master', NOW()),
(120, 'POST', '/api/v2/coe-utilization/**', 'master', NOW()),
(121, 'PUT', '/api/v2/coe-utilization/**', 'master', NOW()),
(122, 'DELETE', '/api/v2/coe-utilization/**', 'master', NOW()),
(123, 'GET', '/api/v2/coe-utilizations/**', 'master', NOW()),
(124, 'POST', '/api/v2/coe-utilizations/**', 'master', NOW()),
(125, 'PUT', '/api/v2/coe-utilizations/**', 'master', NOW()),
(126, 'DELETE', '/api/v2/coe-utilizations/**', 'master', NOW()),

(127, 'GET', '/api/v1/coe-utilization/get-all', 'master', NOW()),
(128, 'GET', '/api/v1/coe-utilization/get', 'master', NOW()),

-------------------employee
(129, 'GET', '/api/v1/employee/**', 'master', NOW()),
(130, 'POST', '/api/v1/employee/**', 'master', NOW()),
(131, 'PUT', '/api/v1/employee/**', 'master', NOW()),
(132, 'DELETE', '/api/v1/employee/**', 'master', NOW()),
(133, 'GET', '/api/v1/employees/**', 'master', NOW()),
(134, 'POST', '/api/v1/employees/**', 'master', NOW()),
(135, 'PUT', '/api/v1/employees/**', 'master', NOW()),
(136, 'DELETE', '/api/v1/employees/**', 'master', NOW()),

(137, 'GET', '/api/v2/employee/**', 'master', NOW()),
(138, 'POST', '/api/v2/employee/**', 'master', NOW()),
(139, 'PUT', '/api/v2/employee/**', 'master', NOW()),
(140, 'DELETE', '/api/v2/employee/**', 'master', NOW()),
(141, 'GET', '/api/v2/employees/**', 'master', NOW()),
(142, 'POST', '/api/v2/employees/**', 'master', NOW()),
(143, 'PUT', '/api/v2/employees/**', 'master', NOW()),
(144, 'DELETE', '/api/v2/employees/**', 'master', NOW()),

(145, 'GET', '/api/v1/employee/search', 'master', NOW()),
(146, 'GET', '/api/v1/employee/details/hccid/{hccId}', 'master', NOW()),
(147, 'GET', '/api/v1/employee/member/{employeeId}', 'master', NOW()),
(148, 'POST', '/api/v1/employee/member/create', 'master', NOW()),
(149, 'PUT', '/api/v1/employee/member/update', 'master', NOW()),
(150, 'DELETE', '/api/v1/employee/delete-employee/{id}', 'master', NOW()),
(151, 'GET', '/api/v1/employee/get-department-level', 'master', NOW()),
(152, 'GET', '/api/v1/employee/get-quantity-of-each-skill', 'master', NOW()),
(153, 'GET', '/api/v1/employee/get-quantity-level', 'master', NOW()),
(154, 'GET', '/api/v1/employee/level', 'master', NOW()),
(155, 'GET', '/api/v1/employee/search-advance', 'master', NOW()),

-------------------employee-evaluation
(156, 'GET', '/api/v1/employee-evaluation/**', 'master', NOW()),
(157, 'POST', '/api/v1/employee-evaluation/**', 'master', NOW()),
(158, 'PUT', '/api/v1/employee-evaluation/**', 'master', NOW()),
(159, 'DELETE', '/api/v1/employee-evaluation/**', 'master', NOW()),
(160, 'GET', '/api/v1/employee-evaluations/**', 'master', NOW()),
(161, 'POST', '/api/v1/employee-evaluations/**', 'master', NOW()),
(162, 'PUT', '/api/v1/employee-evaluations/**', 'master', NOW()),
(163, 'DELETE', '/api/v1/employee-evaluations/**', 'master', NOW()),

(164, 'GET', '/api/v2/employee-evaluation/**', 'master', NOW()),
(165, 'POST', '/api/v2/employee-evaluation/**', 'master', NOW()),
(166, 'PUT', '/api/v2/employee-evaluation/**', 'master', NOW()),
(167, 'DELETE', '/api/v2/employee-evaluation/**', 'master', NOW()),
(168, 'GET', '/api/v2/employee-evaluations/**', 'master', NOW()),
(169, 'POST', '/api/v2/employee-evaluations/**', 'master', NOW()),
(170, 'PUT', '/api/v2/employee-evaluations/**', 'master', NOW()),
(171, 'DELETE', '/api/v2/employee-evaluations/**', 'master', NOW()),

(172, 'GET', '/api/v1/employee-evaluation/details/hccid/{hccId}', 'master', NOW()),

-------------------employee-project
(173, 'GET', '/api/v1/employee-project/**', 'master', NOW()),
(174, 'POST', '/api/v1/employee-project/**', 'master', NOW()),
(175, 'PUT', '/api/v1/employee-project/**', 'master', NOW()),
(176, 'DELETE', '/api/v1/employee-project/**', 'master', NOW()),
(177, 'GET', '/api/v1/employee-projects/**', 'master', NOW()),
(178, 'POST', '/api/v1/employee-projects/**', 'master', NOW()),
(179, 'PUT', '/api/v1/employee-projects/**', 'master', NOW()),
(180, 'DELETE', '/api/v1/employee-projects/**', 'master', NOW()),

(181, 'GET', '/api/v2/employee-project/**', 'master', NOW()),
(182, 'POST', '/api/v2/employee-project/**', 'master', NOW()),
(183, 'PUT', '/api/v2/employee-project/**', 'master', NOW()),
(184, 'DELETE', '/api/v2/employee-project/**', 'master', NOW()),
(185, 'GET', '/api/v2/employee-projects/**', 'master', NOW()),
(186, 'POST', '/api/v2/employee-projects/**', 'master', NOW()),
(187, 'PUT', '/api/v2/employee-projects/**', 'master', NOW()),
(188, 'DELETE', '/api/v2/employee-projects/**', 'master', NOW()),

(189, 'POST', '/api/v1/employee-project/assign/project-id/{projectId}', 'master', NOW()),
(190, 'GET', '/api/v1/employee-project/details/hccid/{hccId}', 'master', NOW()),
(191, 'POST', '/api/v1/employee-project/release', 'master', NOW()),
(192, 'GET', '/api/v1/employee-project/search', 'master', NOW()),
(193, 'GET', '/api/v1/employee-project/project/{projectId}', 'master', NOW()),

-------------------employee-role
(194, 'GET', '/api/v1/employee-role/**', 'master', NOW()),
(195, 'POST', '/api/v1/employee-role/**', 'master', NOW()),
(196, 'PUT', '/api/v1/employee-role/**', 'master', NOW()),
(197, 'DELETE', '/api/v1/employee-role/**', 'master', NOW()),
(198, 'GET', '/api/v1/employee-roles/**', 'master', NOW()),
(199, 'POST', '/api/v1/employee-roles/**', 'master', NOW()),
(200, 'PUT', '/api/v1/employee-roles/**', 'master', NOW()),
(201, 'DELETE', '/api/v1/employee-roles/**', 'master', NOW()),

(202, 'GET', '/api/v2/employee-role/**', 'master', NOW()),
(203, 'POST', '/api/v2/employee-role/**', 'master', NOW()),
(204, 'PUT', '/api/v2/employee-role/**', 'master', NOW()),
(205, 'DELETE', '/api/v2/employee-role/**', 'master', NOW()),
(206, 'GET', '/api/v2/employee-roles/**', 'master', NOW()),
(207, 'POST', '/api/v2/employee-roles/**', 'master', NOW()),
(208, 'PUT', '/api/v2/employee-roles/**', 'master', NOW()),
(209, 'DELETE', '/api/v2/employee-roles/**', 'master', NOW()),

-------------------employee-skill
(210, 'GET', '/api/v1/employee-skill/**', 'master', NOW()),
(211, 'POST', '/api/v1/employee-skill/**', 'master', NOW()),
(212, 'PUT', '/api/v1/employee-skill/**', 'master', NOW()),
(213, 'DELETE', '/api/v1/employee-skill/**', 'master', NOW()),
(214, 'GET', '/api/v1/employee-skills/**', 'master', NOW()),
(215, 'POST', '/api/v1/employee-skills/**', 'master', NOW()),
(216, 'PUT', '/api/v1/employee-skills/**', 'master', NOW()),
(217, 'DELETE', '/api/v1/employee-skills/**', 'master', NOW()),

(218, 'GET', '/api/v2/employee-skill/**', 'master', NOW()),
(219, 'POST', '/api/v2/employee-skill/**', 'master', NOW()),
(220, 'PUT', '/api/v2/employee-skill/**', 'master', NOW()),
(221, 'DELETE', '/api/v2/employee-skill/**', 'master', NOW()),
(222, 'GET', '/api/v2/employee-skills/**', 'master', NOW()),
(223, 'POST', '/api/v2/employee-skills/**', 'master', NOW()),
(224, 'PUT', '/api/v2/employee-skills/**', 'master', NOW()),
(225, 'DELETE', '/api/v2/employee-skills/**', 'master', NOW()),

(226, 'GET', '/api/v1/employee-skill/top-skill', 'master', NOW()),
(227, 'GET', '/api/v1/employee-skill/skill-pie-chart', 'master', NOW()),

-------------------employee-utilization
(228, 'GET', '/api/v1/employee-utilization/**', 'master', NOW()),
(229, 'POST', '/api/v1/employee-utilization/**', 'master', NOW()),
(230, 'PUT', '/api/v1/employee-utilization/**', 'master', NOW()),
(231, 'DELETE', '/api/v1/employee-utilization/**', 'master', NOW()),
(232, 'GET', '/api/v1/employee-utilizations/**', 'master', NOW()),
(233, 'POST', '/api/v1/employee-utilizations/**', 'master', NOW()),
(234, 'PUT', '/api/v1/employee-utilizations/**', 'master', NOW()),
(235, 'DELETE', '/api/v1/employee-utilizations/**', 'master', NOW()),

(236, 'GET', '/api/v2/employee-utilization/**', 'master', NOW()),
(237, 'POST', '/api/v2/employee-utilization/**', 'master', NOW()),
(238, 'PUT', '/api/v2/employee-utilization/**', 'master', NOW()),
(239, 'DELETE', '/api/v2/employee-utilization/**', 'master', NOW()),
(240, 'GET', '/api/v2/employee-utilizations/**', 'master', NOW()),
(241, 'POST', '/api/v2/employee-utilizations/**', 'master', NOW()),
(242, 'PUT', '/api/v2/employee-utilizations/**', 'master', NOW()),
(243, 'DELETE', '/api/v2/employee-utilizations/**', 'master', NOW()),

(244, 'GET', '/api/v1/employee-utilization/pie-chart', 'master', NOW()),
(245, 'GET', '/api/v1/employee-utilization/search', 'master', NOW()),
(246, 'GET', '/api/v1/employee-utilization/detail-HCCID/{hccId}', 'master', NOW()),
(247, 'GET', '/api/v1/employee-utilization/no-utilization', 'master', NOW()),
(248, 'GET', '/api/v1/employee-utilization/detail/{employeeUtilizationId}', 'master', NOW()),
(249, 'GET', '/api/v1/employee-utilization/detail-project/{employeeUtilizationId}', 'master', NOW()),
(250, 'GET', '/api/v1/employee-utilization/no-import-utilization', 'master', NOW()),

-------------------export
(251, 'GET', '/api/v1/export/**', 'master', NOW()),
(252, 'POST', '/api/v1/export/**', 'master', NOW()),
(253, 'PUT', '/api/v1/export/**', 'master', NOW()),
(254, 'DELETE', '/api/v1/export/**', 'master', NOW()),
(255, 'GET', '/api/v1/exports/**', 'master', NOW()),
(256, 'POST', '/api/v1/exports/**', 'master', NOW()),
(257, 'PUT', '/api/v1/exports/**', 'master', NOW()),
(258, 'DELETE', '/api/v1/exports/**', 'master', NOW()),

(259, 'GET', '/api/v2/export/**', 'master', NOW()),
(260, 'POST', '/api/v2/export/**', 'master', NOW()),
(261, 'PUT', '/api/v2/export/**', 'master', NOW()),
(262, 'DELETE', '/api/v2/export/**', 'master', NOW()),
(263, 'GET', '/api/v2/exports/**', 'master', NOW()),
(264, 'POST', '/api/v2/exports/**', 'master', NOW()),
(265, 'PUT', '/api/v2/exports/**', 'master', NOW()),
(266, 'DELETE', '/api/v2/exports/**', 'master', NOW()),

-------------------import-data
(267, 'GET', '/api/v1/import-data/**', 'master', NOW()),
(268, 'POST', '/api/v1/import-data/**', 'master', NOW()),
(269, 'PUT', '/api/v1/import-data/**', 'master', NOW()),
(270, 'DELETE', '/api/v1/import-data/**', 'master', NOW()),
(271, 'GET', '/api/v1/import-datas/**', 'master', NOW()),
(272, 'POST', '/api/v1/import-datas/**', 'master', NOW()),
(273, 'PUT', '/api/v1/import-datas/**', 'master', NOW()),
(274, 'DELETE', '/api/v1/import-datas/**', 'master', NOW()),

(275, 'GET', '/api/v2/import-data/**', 'master', NOW()),
(276, 'POST', '/api/v2/import-data/**', 'master', NOW()),
(277, 'PUT', '/api/v2/import-data/**', 'master', NOW()),
(278, 'DELETE', '/api/v2/import-data/**', 'master', NOW()),
(279, 'GET', '/api/v2/import-datas/**', 'master', NOW()),
(280, 'POST', '/api/v2/import-datas/**', 'master', NOW()),
(281, 'PUT', '/api/v2/import-datas/**', 'master', NOW()),
(282, 'DELETE', '/api/v2/import-datas/**', 'master', NOW()),

-------------------level
(283, 'GET', '/api/v1/level/**', 'master', NOW()),
(284, 'POST', '/api/v1/level/**', 'master', NOW()),
(285, 'PUT', '/api/v1/level/**', 'master', NOW()),
(286, 'DELETE', '/api/v1/level/**', 'master', NOW()),
(287, 'GET', '/api/v1/levels/**', 'master', NOW()),
(288, 'POST', '/api/v1/levels/**', 'master', NOW()),
(289, 'PUT', '/api/v1/levels/**', 'master', NOW()),
(290, 'DELETE', '/api/v1/levels/**', 'master', NOW()),

(291, 'GET', '/api/v2/level/**', 'master', NOW()),
(292, 'POST', '/api/v2/level/**', 'master', NOW()),
(293, 'PUT', '/api/v2/level/**', 'master', NOW()),
(294, 'DELETE', '/api/v2/level/**', 'master', NOW()),
(295, 'GET', '/api/v2/levels/**', 'master', NOW()),
(296, 'POST', '/api/v2/levels/**', 'master', NOW()),
(297, 'PUT', '/api/v2/levels/**', 'master', NOW()),
(298, 'DELETE', '/api/v2/levels/**', 'master', NOW()),

-------------------location
(299, 'GET', '/api/v1/location/**', 'master', NOW()),
(300, 'POST', '/api/v1/location/**', 'master', NOW()),
(301, 'PUT', '/api/v1/location/**', 'master', NOW()),
(302, 'DELETE', '/api/v1/location/**', 'master', NOW()),
(303, 'GET', '/api/v1/locations/**', 'master', NOW()),
(304, 'POST', '/api/v1/locations/**', 'master', NOW()),
(305, 'PUT', '/api/v1/locations/**', 'master', NOW()),
(306, 'DELETE', '/api/v1/locations/**', 'master', NOW()),

(307, 'GET', '/api/v2/location/**', 'master', NOW()),
(308, 'POST', '/api/v2/location/**', 'master', NOW()),
(309, 'PUT', '/api/v2/location/**', 'master', NOW()),
(310, 'DELETE', '/api/v2/location/**', 'master', NOW()),
(311, 'GET', '/api/v2/locations/**', 'master', NOW()),
(312, 'POST', '/api/v2/locations/**', 'master', NOW()),
(313, 'PUT', '/api/v2/locations/**', 'master', NOW()),
(314, 'DELETE', '/api/v2/locations/**', 'master', NOW()),

(315, 'POST', '/api/v1/location/create', 'master', NOW()),
(316, 'PUT', '/api/v1/location/update', 'master', NOW()),
(317, 'GET', '/api/v1/location', 'master', NOW()),

-------------------practice
(318, 'GET', '/api/v1/practice/**', 'master', NOW()),
(319, 'POST', '/api/v1/practice/**', 'master', NOW()),
(320, 'PUT', '/api/v1/practice/**', 'master', NOW()),
(321, 'DELETE', '/api/v1/practice/**', 'master', NOW()),
(322, 'GET', '/api/v1/practices/**', 'master', NOW()),
(323, 'POST', '/api/v1/practices/**', 'master', NOW()),
(324, 'PUT', '/api/v1/practices/**', 'master', NOW()),
(325, 'DELETE', '/api/v1/practices/**', 'master', NOW()),

(326, 'GET', '/api/v2/practice/**', 'master', NOW()),
(327, 'POST', '/api/v2/practice/**', 'master', NOW()),
(328, 'PUT', '/api/v2/practice/**', 'master', NOW()),
(329, 'DELETE', '/api/v2/practice/**', 'master', NOW()),
(330, 'GET', '/api/v2/practices/**', 'master', NOW()),
(331, 'POST', '/api/v2/practices/**', 'master', NOW()),
(332, 'PUT', '/api/v2/practices/**', 'master', NOW()),
(333, 'DELETE', '/api/v2/practices/**', 'master', NOW()),

(334, 'PUT', '/api/v1/practice/update', 'master', NOW()),
(335, 'POST', '/api/v1/practice/create', 'master', NOW()),
(336, 'GET', '/api/v1/practice/get-all-practices', 'master', NOW()),
(337, 'GET', '/api/v1/practice/get-practice/{id}', 'master', NOW()),
(338, 'GET', '/api/v1/practice/get-practices-by-buid/{buId}', 'master', NOW()),

-------------------project
(339, 'GET', '/api/v1/project/**', 'master', NOW()),
(340, 'POST', '/api/v1/project/**', 'master', NOW()),
(341, 'PUT', '/api/v1/project/**', 'master', NOW()),
(342, 'DELETE', '/api/v1/project/**', 'master', NOW()),
(343, 'GET', '/api/v1/projects/**', 'master', NOW()),
(344, 'POST', '/api/v1/projects/**', 'master', NOW()),
(345, 'PUT', '/api/v1/projects/**', 'master', NOW()),
(346, 'DELETE', '/api/v1/projects/**', 'master', NOW()),

(347, 'GET', '/api/v2/project/**', 'master', NOW()),
(348, 'POST', '/api/v2/project/**', 'master', NOW()),
(349, 'PUT', '/api/v2/project/**', 'master', NOW()),
(350, 'DELETE', '/api/v2/project/**', 'master', NOW()),
(351, 'GET', '/api/v2/projects/**', 'master', NOW()),
(352, 'POST', '/api/v2/projects/**', 'master', NOW()),
(353, 'PUT', '/api/v2/projects/**', 'master', NOW()),
(354, 'DELETE', '/api/v2/projects/**', 'master', NOW()),

(355, 'POST', '/api/v1/project/add', 'master', NOW()),
(356, 'GET', '/api/v1/project/search', 'master', NOW()),
(357, 'POST', '/api/v1/project/update', 'master', NOW()),
(358, 'POST', '/api/v1/project/close/{projectId}', 'master', NOW()),
(359, 'GET', '/api/v1/project/detail/{projectId}', 'master', NOW()),
(360, 'POST', '/api/v1/project/update/status/{projectId}/{status}', 'master', NOW()),

-------------------project-feedback
(361, 'GET', '/api/v1/project-feedback/**', 'master', NOW()),
(362, 'POST', '/api/v1/project-feedback/**', 'master', NOW()),
(363, 'PUT', '/api/v1/project-feedback/**', 'master', NOW()),
(364, 'DELETE', '/api/v1/project-feedback/**', 'master', NOW()),
(365, 'GET', '/api/v1/project-feedbacks/**', 'master', NOW()),
(366, 'POST', '/api/v1/project-feedbacks/**', 'master', NOW()),
(367, 'PUT', '/api/v1/project-feedbacks/**', 'master', NOW()),
(368, 'DELETE', '/api/v1/project-feedbacks/**', 'master', NOW()),

(369, 'GET', '/api/v2/project-feedback/**', 'master', NOW()),
(370, 'POST', '/api/v2/project-feedback/**', 'master', NOW()),
(371, 'PUT', '/api/v2/project-feedback/**', 'master', NOW()),
(372, 'DELETE', '/api/v2/project-feedback/**', 'master', NOW()),
(373, 'GET', '/api/v2/project-feedbacks/**', 'master', NOW()),
(374, 'POST', '/api/v2/project-feedbacks/**', 'master', NOW()),
(375, 'PUT', '/api/v2/project-feedbacks/**', 'master', NOW()),
(376, 'DELETE', '/api/v2/project-feedbacks/**', 'master', NOW()),

(377, 'POST', '/api/v1/project-feedback/add', 'master', NOW()),

-------------------project-type
(378, 'GET', '/api/v1/project-type/**', 'master', NOW()),
(379, 'POST', '/api/v1/project-type/**', 'master', NOW()),
(380, 'PUT', '/api/v1/project-type/**', 'master', NOW()),
(381, 'DELETE', '/api/v1/project-type/**', 'master', NOW()),
(382, 'GET', '/api/v1/project-types/**', 'master', NOW()),
(383, 'POST', '/api/v1/project-types/**', 'master', NOW()),
(384, 'PUT', '/api/v1/project-types/**', 'master', NOW()),
(385, 'DELETE', '/api/v1/project-types/**', 'master', NOW()),

(386, 'GET', '/api/v2/project-type/**', 'master', NOW()),
(387, 'POST', '/api/v2/project-type/**', 'master', NOW()),
(388, 'PUT', '/api/v2/project-type/**', 'master', NOW()),
(389, 'DELETE', '/api/v2/project-type/**', 'master', NOW()),
(390, 'GET', '/api/v2/project-types/**', 'master', NOW()),
(391, 'POST', '/api/v2/project-types/**', 'master', NOW()),
(392, 'PUT', '/api/v2/project-types/**', 'master', NOW()),
(393, 'DELETE', '/api/v2/project-types/**', 'master', NOW()),

(394, 'GET', '/api/v1/project-type/get-all-project-type', 'master', NOW()),

-------------------skill-set
(395, 'GET', '/api/v1/skill-set/**', 'master', NOW()),
(396, 'POST', '/api/v1/skill-set/**', 'master', NOW()),
(397, 'PUT', '/api/v1/skill-set/**', 'master', NOW()),
(398, 'DELETE', '/api/v1/skill-set/**', 'master', NOW()),
(399, 'GET', '/api/v1/skill-sets/**', 'master', NOW()),
(400, 'POST', '/api/v1/skill-sets/**', 'master', NOW()),
(401, 'PUT', '/api/v1/skill-sets/**', 'master', NOW()),
(402, 'DELETE', '/api/v1/skill-sets/**', 'master', NOW()),

(403, 'GET', '/api/v2/skill-set/**', 'master', NOW()),
(404, 'POST', '/api/v2/skill-set/**', 'master', NOW()),
(405, 'PUT', '/api/v2/skill-set/**', 'master', NOW()),
(406, 'DELETE', '/api/v2/skill-set/**', 'master', NOW()),
(407, 'GET', '/api/v2/skill-sets/**', 'master', NOW()),
(408, 'POST', '/api/v2/skill-sets/**', 'master', NOW()),
(409, 'PUT', '/api/v2/skill-sets/**', 'master', NOW()),
(410, 'DELETE', '/api/v2/skill-sets/**', 'master', NOW()),

(411, 'GET', '/api/v1/skill-set/list-skills-by-name', 'master', NOW()),

-------------------user
(412, 'GET', '/api/v1/user/**', 'master', NOW()),
(413, 'POST', '/api/v1/user/**', 'master', NOW()),
(414, 'PUT', '/api/v1/user/**', 'master', NOW()),
(415, 'DELETE', '/api/v1/user/**', 'master', NOW()),
(416, 'GET', '/api/v1/users/**', 'master', NOW()),
(417, 'POST', '/api/v1/users/**', 'master', NOW()),
(418, 'PUT', '/api/v1/users/**', 'master', NOW()),
(419, 'DELETE', '/api/v1/users/**', 'master', NOW()),

(420, 'GET', '/api/v2/user/**', 'master', NOW()),
(421, 'POST', '/api/v2/user/**', 'master', NOW()),
(422, 'PUT', '/api/v2/user/**', 'master', NOW()),
(423, 'DELETE', '/api/v2/user/**', 'master', NOW()),
(424, 'GET', '/api/v2/users/**', 'master', NOW()),
(425, 'POST', '/api/v2/users/**', 'master', NOW()),
(426, 'PUT', '/api/v2/users/**', 'master', NOW()),
(427, 'DELETE', '/api/v2/users/**', 'master', NOW()),

-------------------common-status
(428, 'GET', '/api/v1/common-status/**', 'master', NOW()),
(429, 'POST', '/api/v1/common-status/**', 'master', NOW()),
(430, 'PUT', '/api/v1/common-status/**', 'master', NOW()),
(431, 'DELETE', '/api/v1/common-status/**', 'master', NOW()),
(432, 'GET', '/api/v1/common-statuses/**', 'master', NOW()),
(433, 'POST', '/api/v1/common-statuses/**', 'master', NOW()),
(434, 'PUT', '/api/v1/common-statuses/**', 'master', NOW()),
(435, 'DELETE', '/api/v1/common-statuses/**', 'master', NOW()),

(436, 'GET', '/api/v2/common-status/**', 'master', NOW()),
(437, 'POST', '/api/v2/common-status/**', 'master', NOW()),
(438, 'PUT', '/api/v2/common-status/**', 'master', NOW()),
(439, 'DELETE', '/api/v2/common-status/**', 'master', NOW()),
(440, 'GET', '/api/v2/common-statuses/**', 'master', NOW()),
(441, 'POST', '/api/v2/common-statuses/**', 'master', NOW()),
(442, 'PUT', '/api/v2/common-statuses/**', 'master', NOW()),
(443, 'DELETE', '/api/v2/common-statuses/**', 'master', NOW()),

-------------------feedback-template
(444, 'GET', '/api/v1/feedback-template/**', 'master', NOW()),
(445, 'POST', '/api/v1/feedback-template/**', 'master', NOW()),
(446, 'PUT', '/api/v1/feedback-template/**', 'master', NOW()),
(447, 'DELETE', '/api/v1/feedback-template/**', 'master', NOW()),
(448, 'GET', '/api/v1/feedback-templates/**', 'master', NOW()),
(449, 'POST', '/api/v1/feedback-templates/**', 'master', NOW()),
(450, 'PUT', '/api/v1/feedback-templates/**', 'master', NOW()),
(451, 'DELETE', '/api/v1/feedback-templates/**', 'master', NOW()),

(452, 'GET', '/api/v2/feedback-template/**', 'master', NOW()),
(453, 'POST', '/api/v2/feedback-template/**', 'master', NOW()),
(454, 'PUT', '/api/v2/feedback-template/**', 'master', NOW()),
(455, 'DELETE', '/api/v2/feedback-template/**', 'master', NOW()),
(456, 'GET', '/api/v2/feedback-templates/**', 'master', NOW()),
(457, 'POST', '/api/v2/feedback-templates/**', 'master', NOW()),
(458, 'PUT', '/api/v2/feedback-templates/**', 'master', NOW()),
(459, 'DELETE', '/api/v2/feedback-templates/**', 'master', NOW()),

-------------------feedback-template-attribute
(460, 'GET', '/api/v1/feedback-template-attribute/**', 'master', NOW()),
(461, 'POST', '/api/v1/feedback-template-attribute/**', 'master', NOW()),
(462, 'PUT', '/api/v1/feedback-template-attribute/**', 'master', NOW()),
(463, 'DELETE', '/api/v1/feedback-template-attribute/**', 'master', NOW()),
(464, 'GET', '/api/v1/feedback-template-attributes/**', 'master', NOW()),
(465, 'POST', '/api/v1/feedback-template-attributes/**', 'master', NOW()),
(466, 'PUT', '/api/v1/feedback-template-attributes/**', 'master', NOW()),
(467, 'DELETE', '/api/v1/feedback-template-attributes/**', 'master', NOW()),

(468, 'GET', '/api/v2/feedback-template-attribute/**', 'master', NOW()),
(469, 'POST', '/api/v2/feedback-template-attribute/**', 'master', NOW()),
(470, 'PUT', '/api/v2/feedback-template-attribute/**', 'master', NOW()),
(471, 'DELETE', '/api/v2/feedback-template-attribute/**', 'master', NOW()),
(472, 'GET', '/api/v2/feedback-template-attributes/**', 'master', NOW()),
(473, 'POST', '/api/v2/feedback-template-attributes/**', 'master', NOW()),
(474, 'PUT', '/api/v2/feedback-template-attributes/**', 'master', NOW()),
(475, 'DELETE', '/api/v2/feedback-template-attributes/**', 'master', NOW()),

-------------------feedback-template-column
(476, 'GET', '/api/v1/feedback-template-column/**', 'master', NOW()),
(477, 'POST', '/api/v1/feedback-template-column/**', 'master', NOW()),
(478, 'PUT', '/api/v1/feedback-template-column/**', 'master', NOW()),
(479, 'DELETE', '/api/v1/feedback-template-column/**', 'master', NOW()),
(480, 'GET', '/api/v1/feedback-template-columns/**', 'master', NOW()),
(481, 'POST', '/api/v1/feedback-template-columns/**', 'master', NOW()),
(482, 'PUT', '/api/v1/feedback-template-columns/**', 'master', NOW()),
(483, 'DELETE', '/api/v1/feedback-template-columns/**', 'master', NOW()),

(484, 'GET', '/api/v2/feedback-template-column/**', 'master', NOW()),
(485, 'POST', '/api/v2/feedback-template-column/**', 'master', NOW()),
(486, 'PUT', '/api/v2/feedback-template-column/**', 'master', NOW()),
(487, 'DELETE', '/api/v2/feedback-template-column/**', 'master', NOW()),
(488, 'GET', '/api/v2/feedback-template-columns/**', 'master', NOW()),
(489, 'POST', '/api/v2/feedback-template-columns/**', 'master', NOW()),
(490, 'PUT', '/api/v2/feedback-template-columns/**', 'master', NOW()),
(491, 'DELETE', '/api/v2/feedback-template-columns/**', 'master', NOW()),

-------------------project-feedback-detail
(492, 'GET', '/api/v1/project-feedback-detail/**', 'master', NOW()),
(493, 'POST', '/api/v1/project-feedback-detail/**', 'master', NOW()),
(494, 'PUT', '/api/v1/project-feedback-detail/**', 'master', NOW()),
(495, 'DELETE', '/api/v1/project-feedback-detail/**', 'master', NOW()),
(496, 'GET', '/api/v1/project-feedback-details/**', 'master', NOW()),
(497, 'POST', '/api/v1/project-feedback-details/**', 'master', NOW()),
(498, 'PUT', '/api/v1/project-feedback-details/**', 'master', NOW()),
(499, 'DELETE', '/api/v1/project-feedback-details/**', 'master', NOW()),

(500, 'GET', '/api/v2/project-feedback-detail/**', 'master', NOW()),
(501, 'POST', '/api/v2/project-feedback-detail/**', 'master', NOW()),
(502, 'PUT', '/api/v2/project-feedback-detail/**', 'master', NOW()),
(503, 'DELETE', '/api/v2/project-feedback-detail/**', 'master', NOW()),
(504, 'GET', '/api/v2/project-feedback-details/**', 'master', NOW()),
(505, 'POST', '/api/v2/project-feedback-details/**', 'master', NOW()),
(506, 'PUT', '/api/v2/project-feedback-details/**', 'master', NOW()),
(507, 'DELETE', '/api/v2/project-feedback-details/**', 'master', NOW());


INSERT INTO public.group_right(id, group_id, right_id, created_by, created_date)
VALUES
(1,1,1,'master',now()),
(2,1,2,'master',now()),
(3,1,3,'master',now()),
(4,1,4,'master',now());