/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 06-Jul-2023 4:51:28 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE "coe_utilization"
(
	"id" SERIAL NOT NULL,
	"duration" varchar(50) NOT NULL, -- Example: "Duration: 01 Mar 2023 - 31 Mar 2023"
	"start_date" timestamp NOT NULL,
	"end_date" timestamp NOT NULL,
	"total_utilization" FLOAT NOT NULL DEFAULT 0.0,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "employee_role"
(
	"id" SERIAL NOT NULL,
	"code" varchar(50)	 NOT NULL,
	"name" varchar(50)	 NULL,
	"description" varchar(250)	 NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "employee_utilization"
(
	"id" SERIAL NOT NULL,
	"code" uuid NOT NULL,
	"coe_utilization_id" integer NOT NULL,
	"employee_id" integer NOT NULL,
    "project_code" varchar(50)	 NOT NULL,
	"billable_hours" integer NOT NULL DEFAULT 0,
	"logged_hours" integer NOT NULL DEFAULT 0,
	"billable" FLOAT NOT NULL DEFAULT 0, -- ideal case: billable == employee_project.utilization
	"pto_oracle" integer NOT NULL DEFAULT 0,
	"available_hours" integer NOT NULL DEFAULT 0,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "user"
(
	"id" SERIAL NOT NULL,
	"name" varchar(100)	 NOT NULL,
	"email" varchar(50)	 NOT NULL,
	"password" varchar(255) NOT NULL,
	"group_id" integer NOT NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "survey_data"
(
	"id" SERIAL NOT NULL,
	"start_time" date NOT NULL,
	"completion_time" date NOT NULL,
	"email" varchar(50)	 NULL,
	"name" varchar(50)	 NULL,
	"employee_id" varchar(50)	 NOT NULL,
	"full_name" varchar(100)	 NOT NULL,
	"current_address" varchar(200)	 NULL,
	"english" varchar(100)	 NULL,
	"japanese" varchar(50)	 NULL,
	"certificate" varchar(50)	 NULL,
	"waterfall" integer NULL,
	"agile" integer NULL,
	"manufacturing" varchar(100) NULL,
	"semiconductor" varchar(100) NULL,
	"transportation" varchar(100) NULL,
	"iot_lumada" varchar(100) NULL,
	"energy_utilities" varchar(100) NULL,
	"retail_logistic" varchar(100) NULL,
	"automotive" varchar(100) NULL,
	"finance_banking" varchar(100) NULL,
	"insurrance" varchar(100) NULL,
	"healthcare" varchar(100) NULL,
	"printing" varchar(100) NULL,
	"smart_space" varchar(100) NULL,
	"other" varchar(100) NULL,
	"c" integer NULL,
	"c#" integer NULL,
	"java" integer NULL,
	"golang" integer NULL,
	"kotlin" integer NULL,
	"python" integer NULL,
	"r" integer NULL,
	"php" integer NULL,
	"visual_basic.net" integer NULL,
	"visual_basic_6" integer NULL,
	"css_html5" integer NULL,
	"javascript" integer NULL,
	"bootstrap_or_material" integer NULL,
	"jquery" integer NULL,
	"angular" integer NULL,
	"angularjs" integer NULL,
	"react" integer NULL,
	"nestjs" integer NULL,
	"vuejs" integer NULL,
	"sencha" integer NULL,
	"react_native" integer NULL,
	"prism" integer NULL,
	"flutter" integer NULL,
	"typescript" integer NULL,
	"java-spring_boot" integer NULL,
	"java-spring_mvc" integer NULL,
	"java-jsp" integer NULL,
	"java_play_framework" integer NULL,
	".net_core" integer NULL,
	"vb.net" integer NULL,
	"asp.net" integer NULL,
	"python_flask" integer NULL,
	"python_django" integer NULL,
	"go" integer NULL,
	"kotlin2" integer NULL,
	"quarkus" integer NULL,
	"micronaut" integer NULL,
	"nodered" integer NULL,
	"nodejs" integer NULL,
	"oracle_pl_or_sql" integer NULL,
	"iot_websocket" integer NULL,
	"iot_thinkworx" integer NULL,
	"iot_mqtt" integer NULL,
	".net_winform" integer NULL,
	".net_wpf" integer NULL,
	"java_swing" integer NULL,
	"javafx" integer NULL,
	"oracle_form_or_report" integer NULL,
	"websphere_application_server" integer NULL,
	"jboss_or_wildfly" integer NULL,
	"iis" integer NULL,
	"tomcat" integer NULL,
	"netty" integer NULL,
	"maven" integer NULL,
	"gradle" integer NULL,
	"oracle_db" integer NULL,
	"postgresql" integer NULL,
	"mysql" integer NULL,
	"mariadb" integer NULL,
	"sql_server" integer NULL,
	"db2" integer NULL,
	"influxdb" integer NULL,
	"prometheus" integer NULL,
	"druid" integer NULL,
	"azure_time_series_insight" integer NULL,
	"aws_timestream" integer NULL,
	"mongodb" integer NULL,
	"cassandra" integer NULL,
	"couchbase" integer NULL,
	"neo4j" integer NULL,
	"arangodb" integer NULL,
	"camunda" integer NULL,
	"wps_soa" integer NULL,
	"mulesoft" integer NULL,
	"cqrs" integer NULL,
	"saga" integer NULL,
	"circuit_breaker" integer NULL,
	"kong" integer NULL,
	"aws_api_gateway" integer NULL,
	"azure_api_management" integer NULL,
	"tyk" integer NULL,
	"wso2" integer NULL,
	"apigee" integer NULL,
	"keycloak" integer NULL,
	"okta" integer NULL,
	"azure_ad" integer NULL,
	"auth0" integer NULL,
	"aws_iam" integer NULL,
	"apache_spark" integer NULL,
	"apache_nifi" integer NULL,
	"rabbitmq" integer NULL,
	"kafka" integer NULL,
	"active_mq" integer NULL,
	"microsoft_biztalk" integer NULL,
	"tibco_ems" integer NULL,
	"redis" integer NULL,
	"memcached" integer NULL,
	"apache_ignite" integer NULL,
	"elasticsearch" integer NULL,
	"nginx" integer NULL,
	"haproxy" integer NULL,
	"fundamentals" integer NULL,
	"ci/cd_tools" integer NULL,
	"networking" integer NULL,
	"security_lib" integer NULL,
	"virtual_machine" integer NULL,
	"build_or_compose" integer NULL,
	"docker" integer NULL,
	"sonarqube" integer NULL,
	"kubernetes" integer NULL,
	"jenkin" integer NULL,
	"jira" integer NULL,
	"svn" integer NULL,
	"gitlab" integer NULL,
	"github" integer NULL,
	"bitbucket" integer NULL,
	"azure_repos" integer NULL,
	"aws_codecommit" integer NULL,
	"tableau" integer NULL,
	"power_bi" integer NULL,
	"pentaho" integer NULL,
	"qlikview" integer NULL,
	"google_data_studio" integer NULL,
	"ibm_cognos" integer NULL,
	"qlik_sense" integer NULL,
	"aws" integer NULL,
	"ui_automation" integer NULL,
	"azure" integer NULL,
	"api_tool" integer NULL,
	"performance" integer NULL,
	"gcp" integer NULL,
	"security" integer NULL,
	"couldstack" integer NULL,
	"openstack" integer NULL,
	"localstack" integer NULL,
	"pcf" integer NULL,
	"saleforce" integer NULL,
	"oci" integer NULL,
	"ansible" integer NULL,
	"terraform" integer NULL,
	"adobe_figma" integer NULL,
	"adobe_xd" integer NULL,
	"invision" integer NULL,
	"sketch" integer NULL,
	"flinto" integer NULL,
	"framer" integer NULL,
	"ux_pin" integer NULL,
	"wireframe_balsamiq" integer NULL,
	"motion_design" integer NULL,
	"adobe_photoshop" integer NULL,
	"adobe_illustrator" integer NULL,
	"adobe_express" integer NULL,
	"adobe_indesign" integer NULL,
	"adobe_premiere_pro" integer NULL,
	"adobe_after_effects" integer NULL,
	"adobe_audition" integer NULL,
	"adobe_animate" integer NULL,
	"material_design" integer NULL,
	"apple_human_interface_guidelines"  integer NULL,
	"mui_theme" integer NULL,
	"hitachi_next_theme" integer NULL,
	"w3c" integer NULL,
	"csun_accessibility"  integer NULL,
	"ux_researcher"  integer NULL,
	"ux_writing" integer NULL,
	"angular_style_theme" integer NULL,
	"react_style_theme" integer NULL,
	"wpf_style_theme" integer NULL,
	"sass_css" integer NULL,
	"less_css" integer NULL,
	"other_skills" varchar(250) NULL
)
;

CREATE TABLE "skill_set"
(
	"id" SERIAL NOT NULL,
	"code" varchar(50)	 NOT NULL,
	"name" varchar(250)	 NULL,
	"description" varchar(50)	 NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "right"
(
	"id" integer not null,
	"code" varchar(50)	 NOT NULL,
	"module" varchar(200)	 NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "project_type"
(
	"id" integer NOT NULL,
	"code" varchar(50)	 NOT NULL,
	"name" varchar(250)	 NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "project_tech"
(
	"id" SERIAL NOT NULL,
	"project_id" integer NOT NULL,
	"skill_set_id" integer NOT NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "project_feedback"
(
	"id" SERIAL NOT NULL,
	"project_id" integer NOT NULL,
	"employee_id" integer NOT NULL,
	"project_manager" varchar(50)	 NOT NULL,
	"evaluation_level_id" integer NULL,
	"feedback" text NULL,
	"feedback_date" timestamp NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "project"
(
	"id" SERIAL NOT NULL,
	"code" varchar(50)	 NOT NULL,    -- oracle project code
	"name" varchar(100)	 NULL,
	"description" varchar(250)	 NULL,
	"customer_name" varchar(100)	 NULL,
	"project_manager" varchar(100)	 NOT NULL,
	"business_domain_id" integer NOT NULL,
	"business_unit_id" integer NOT NULL,
	"project_type_id" integer NOT NULL,
	"status" smallint NOT NULL DEFAULT 1, -- 1 On Hold -- 2 Investigate -- 3 Open -- 4 Close -- 5 ReOpen
	"start_date" timestamp NOT NULL,
	"end_date" timestamp NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "practice"
(
	"id" integer NOT NULL,
	"business_unit_id" integer NOT NULL,
	"code" varchar(50)	 NOT NULL,
	"name" varchar(250)	 NULL,
	"description" varchar(250)	 NULL,
	"manager" varchar(50)	 NOT NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "location"
(
	"id" integer NOT NULL,
	"code" varchar(50)	 NOT NULL,
	"name" varchar(100)	 NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "level"
(
	"id" integer NOT NULL,
	"code" varchar(50)	 NOT NULL,
	"name" varchar(100)	 NULL,
	"description" varchar(250)	 NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "group_right"
(
	"id" SERIAL NOT NULL,
	"group_id" integer NOT NULL,
	"right_id" integer NOT NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "group"
(
	"id" integer NOT NULL,
	"code" varchar(50)	 NOT NULL,
	"name" varchar(200)	 NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "evaluation_level"
(
	"id" SERIAL NOT NULL,
	"code" varchar(50)	 NOT NULL,
	"description" varchar(250)	 NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "employee_status"
(
	"id" SERIAL NOT NULL,
	"status_date" timestamp NOT NULL,
	"employee_id" integer NOT NULL,
	"status" smallint NULL
)
;

CREATE TABLE "employee_skill"
(
	"id" SERIAL NOT NULL,
	"employee_id" integer NOT NULL,
	"skill_set_id" integer NULL,
	"skill_set_date" timestamp NOT NULL,
	"skill_level" integer NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "employee_project"
(
	"id" SERIAL NOT NULL,
	"employee_id" integer NOT NULL,
	"project_id" integer NOT NULL,
	"start_date" timestamp NOT NULL,
	"employee_type" integer NULL,    -- 0: shadow acc 1: official acc
	"end_date" timestamp NULL,
	"release_date" timestamp NULL,
	"utilization" integer NOT NULL DEFAULT 0, -- %utilization/%billable
	"description" varchar(250) NULL,
	"employee_role_id" integer NOT NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "employee_level"
(
	"id" SERIAL NOT NULL,
	"employee_id" integer NOT NULL,
	"level_id" integer NOT NULL,
	"level_date" timestamp NOT NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "employee_evaluation"
(
	"id" SERIAL NOT NULL,
	"employee_id" integer NOT NULL,
	"evaluation_date" date NOT NULL,
	"evaluation_info" text NULL,
	"evaluator_id" integer NOT NULL,
	"evaluation_level_id" integer NOT NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "employee"
(
	"id" SERIAL NOT NULL,
	"ldap" varchar(50)	 NOT NULL,
	"hcc_id" varchar(50)	 NOT NULL,
	"name" varchar(100)	 NOT NULL,
	"email" varchar(50)	 NOT NULL,
	"legal_entity_hire_date" date NOT NULL,
	"business_unit_id" integer NOT NULL, 
	"branch_id" integer NOT NULL,
	"coe_core_team_id" integer NOT NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "coe_core_team"
(
	"id" SERIAL NOT NULL,
	"code" varchar(50)	 NOT NULL,
	"name" varchar(250)	 NULL,
	"coe_id" integer NOT NULL,
	"sub_leader_id" integer NOT NULL,
	"status" smallint NOT NULL DEFAULT 1,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "center_of_excellence"
(
	"id" integer NOT NULL,
	"code" varchar(50)	 NOT NULL,
	"name" varchar(250)	 NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "business_unit"
(
	"id" integer NOT NULL,
	"code" varchar(10)	 NOT NULL,
	"name" varchar(50)	 NULL,
	"description" varchar(250)	 NULL,
	"manager" varchar(50)	 NOT NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "business_domain"
(
	"id" integer NOT NULL,
	"code" varchar(50)	 NOT NULL,
	"name" varchar(250)	 NULL,
	"description" text NULL,
	"practice_id" integer NOT NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

CREATE TABLE "branch"
(
	"id" integer NOT NULL,
	"code" varchar(50)	 NOT NULL,
	"name" varchar(250)	 NULL,
	"location_id" integer NOT NULL,
	"created_by" varchar(50)	 NOT NULL,
	"created_date" timestamp NOT NULL,
	"updated_by" varchar(50)	 NULL,
	"updated_date" timestamp NULL
)
;

/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON COLUMN "project"."code"
	IS 'oracle project code'
;

COMMENT ON TABLE "evaluation_level"
	IS 'Performance Rating     Outstanding     Exceeds Expectation     Meets Expectation 3     Meets Expectation 2     Meets Expectation 1     Need support'
;

COMMENT ON COLUMN "employee_project"."employee_type"
	IS '0: shadow acc 1: official acc'
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "coe_utilization" ADD CONSTRAINT "PK_coe_utilization"
	PRIMARY KEY ("id")
;

ALTER TABLE "employee_utilization" ADD CONSTRAINT "PK_employee_utilization"
	PRIMARY KEY ("id")
;

CREATE INDEX "IXFK_employee_utilization_employee" ON "employee_utilization" ("employee_id" ASC)
;

CREATE INDEX "IXFK_employee_utilization_coe_utilization" ON "employee_utilization" ("coe_utilization_id" ASC)
;

ALTER TABLE "user" ADD CONSTRAINT "PK_user"
	PRIMARY KEY ("id")
;

CREATE INDEX "IXFK_user_group" ON "user" ("group_id" ASC)
;

ALTER TABLE "survey_data" ADD CONSTRAINT "PK_SurveyData"
	PRIMARY KEY ("id")
;

ALTER TABLE "skill_set" ADD CONSTRAINT "PK_skill_set"
	PRIMARY KEY ("id")
;

ALTER TABLE "skill_set" ADD CONSTRAINT "UNIQ_skill_set_code" UNIQUE ("code")
;

ALTER TABLE "right" ADD CONSTRAINT "PK_right"
	PRIMARY KEY ("id")
;

ALTER TABLE "project_type" ADD CONSTRAINT "PK_project_type"
	PRIMARY KEY ("id")
;

ALTER TABLE "project_type" ADD CONSTRAINT "UNIQ_project_type_code" UNIQUE ("code")
;

ALTER TABLE "project_tech" ADD CONSTRAINT "PK_project_tech"
	PRIMARY KEY ("id")
;

CREATE INDEX "IXFK_Project_Tech_Project" ON "project_tech" ("project_id" ASC)
;

CREATE INDEX "IXFK_Project_Tech_Skill_set" ON "project_tech" ("skill_set_id" ASC)
;

ALTER TABLE "project_feedback" ADD CONSTRAINT "PK_project_feedback"
	PRIMARY KEY ("id")
;

CREATE INDEX "IXFK_Project_feedback_Employee" ON "project_feedback" ("employee_id" ASC)
;

CREATE INDEX "IXFK_project_feedback_evaluation_level" ON "project_feedback" ("evaluation_level_id" ASC)
;

CREATE INDEX "IXFK_Project_feedback_Project" ON "project_feedback" ("project_id" ASC)
;

ALTER TABLE "project" ADD CONSTRAINT "PK_project"
	PRIMARY KEY ("id")
;

ALTER TABLE "project" ADD CONSTRAINT "UNIQ_project_code" UNIQUE ("code")
;

CREATE INDEX "IXFK_Project_BusinessDomain" ON "project" ("business_domain_id" ASC)
;

CREATE INDEX "IXFK_Project_ProjectType" ON "project" ("project_type_id" ASC)
;

ALTER TABLE "practice" ADD CONSTRAINT "PK_Practice"
	PRIMARY KEY ("id")
;

ALTER TABLE "practice" ADD CONSTRAINT "UNIQ_practice_code" UNIQUE ("code")
;

CREATE INDEX "IXFK_Practice_BusinessUnit" ON "practice" ("business_unit_id" ASC)
;

ALTER TABLE "location" ADD CONSTRAINT "PK_location"
	PRIMARY KEY ("id")
;

ALTER TABLE "location" ADD CONSTRAINT "UNIQ_location_code" UNIQUE ("code")
;

ALTER TABLE "level" ADD CONSTRAINT "PK_level"
	PRIMARY KEY ("id")
;

ALTER TABLE "level" ADD CONSTRAINT "UNIQ_level_code" UNIQUE ("code")
;

ALTER TABLE "group_right" ADD CONSTRAINT "PK_group_right"
	PRIMARY KEY ("id")
;

CREATE INDEX "IXFK_group_right_group" ON "group_right" ("group_id" ASC)
;

CREATE INDEX "IXFK_group_right_right" ON "group_right" ("right_id" ASC)
;

ALTER TABLE "group" ADD CONSTRAINT "PK_group"
	PRIMARY KEY ("id")
;

ALTER TABLE "evaluation_level" ADD CONSTRAINT "PK_evaluation_level"
	PRIMARY KEY ("id")
;

ALTER TABLE "evaluation_level" ADD CONSTRAINT "UNIQ_evaluation_level_code" UNIQUE ("code")
;

ALTER TABLE "employee_status" ADD CONSTRAINT "PK_employee_status"
	PRIMARY KEY ("id")
;


CREATE INDEX "IXFK_employee_status_employee" ON "employee_status" ("employee_id" ASC)
;

ALTER TABLE "employee_skill" ADD CONSTRAINT "PK_EmployeeSkill"
	PRIMARY KEY ("id")
;

CREATE INDEX "IXFK_employee_skill_employee" ON "employee_skill" ("employee_id" ASC)
;

CREATE INDEX "IXFK_employee_skill_skill_set" ON "employee_skill" ("skill_set_id" ASC)
;

ALTER TABLE "employee_project" ADD CONSTRAINT "PK_Table1"
	PRIMARY KEY ("id")
;

CREATE INDEX "IXFK_employ_project_employee" ON "employee_project" ("employee_id" ASC)
;

CREATE INDEX "IXFK_employ_project_project" ON "employee_project" ("project_id" ASC)
;

ALTER TABLE "employee_level" ADD CONSTRAINT "PK_Employee_level"
	PRIMARY KEY ("id")
;

CREATE INDEX "IXFK_Employee_level_Employee" ON "employee_level" ("employee_id" ASC)
;

CREATE INDEX "IXFK_Employee_level_level" ON "employee_level" ("level_id" ASC)
;

ALTER TABLE "employee_evaluation" ADD CONSTRAINT "PK_employee_evaluation"
	PRIMARY KEY ("id")
;

CREATE INDEX "IXFK_employee_evaluation_employee" ON "employee_evaluation" ("employee_id" ASC)
;

CREATE INDEX "IXFK_employee_evaluation_evaluation_level" ON "employee_evaluation" ("evaluation_level_id" ASC)
;

ALTER TABLE "employee" ADD CONSTRAINT "PK_Employee"
	PRIMARY KEY ("id")
;

ALTER TABLE "employee" ADD CONSTRAINT "UNIQ_ldap" UNIQUE ("ldap")
;

ALTER TABLE "employee" ADD CONSTRAINT "UNIQ_hcc_id" UNIQUE ("hcc_id")
;

ALTER TABLE "employee" ADD CONSTRAINT "UNIQ_email" UNIQUE ("email")
;

CREATE INDEX "IXFK_employee_branch" ON "employee" ("id" ASC)
;

CREATE INDEX "IXFK_employee_business_unit" ON "employee" ("business_unit_id" ASC)
;

CREATE INDEX "IXFK_employee_coe_core_team" ON "employee" ("coe_core_team_id" ASC)
;

ALTER TABLE "coe_core_team" ADD CONSTRAINT "PK_coe_core_team"
	PRIMARY KEY ("id")
;

ALTER TABLE "coe_core_team" ADD CONSTRAINT "UNIQ_core_team_code" UNIQUE ("code")
;

CREATE INDEX "IXFK_coe_core_team_center_of_excellence" ON "coe_core_team" ("coe_id" ASC)
;

ALTER TABLE "center_of_excellence" ADD CONSTRAINT "PK_center_of_excellence"
	PRIMARY KEY ("id")
;

ALTER TABLE "center_of_excellence" ADD CONSTRAINT "UNIQ_coe_code" UNIQUE ("code")
;

ALTER TABLE "business_unit" ADD CONSTRAINT "PK_BusinessUnit"
	PRIMARY KEY ("id")
;

ALTER TABLE "business_unit" ADD CONSTRAINT "UNIQ_business_unit_code" UNIQUE ("code")
;

ALTER TABLE "business_domain" ADD CONSTRAINT "PK_BusinessDomain"
	PRIMARY KEY ("id")
;

ALTER TABLE "business_domain" ADD CONSTRAINT "UNIQ_business_domain_code" UNIQUE ("code")
;

CREATE INDEX "IXFK_BusinessDomain_Practice" ON "business_domain" ("practice_id" ASC)
;

ALTER TABLE "branch" ADD CONSTRAINT "PK_branch"
	PRIMARY KEY ("id")
;

ALTER TABLE "branch" ADD CONSTRAINT "UNIQ_branch_code" UNIQUE ("code")
;

ALTER TABLE "employee_role" ADD CONSTRAINT "PK_EmployeeRole"
	PRIMARY KEY ("id")
;

ALTER TABLE "employee_role" ADD CONSTRAINT "UNIQ_employee_role_code" UNIQUE ("code")
;

/* Create Foreign Key Constraints */

ALTER TABLE "employee_utilization" ADD CONSTRAINT "FK_employee_utilization_employee"
	FOREIGN KEY ("employee_id") REFERENCES "employee" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "employee_utilization" ADD CONSTRAINT "FK_employee_utilization_coe_utilization"
	FOREIGN KEY ("coe_utilization_id") REFERENCES "coe_utilization" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "user" ADD CONSTRAINT "FK_user_group"
	FOREIGN KEY ("group_id") REFERENCES "group" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "project_tech" ADD CONSTRAINT "FK_Project_Tech_Project"
	FOREIGN KEY ("project_id") REFERENCES "project" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "project_tech" ADD CONSTRAINT "FK_Project_Tech_Skill_set"
	FOREIGN KEY ("skill_set_id") REFERENCES "skill_set" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "project_feedback" ADD CONSTRAINT "FK_Project_feedback_Employee"
	FOREIGN KEY ("employee_id") REFERENCES "employee" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "project_feedback" ADD CONSTRAINT "FK_project_feedback_evaluation_level"
	FOREIGN KEY ("evaluation_level_id") REFERENCES "evaluation_level" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "project_feedback" ADD CONSTRAINT "FK_Project_feedback_Project"
	FOREIGN KEY ("project_id") REFERENCES "project" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "project" ADD CONSTRAINT "FK_Project_BusinessDomain"
	FOREIGN KEY ("business_domain_id") REFERENCES "business_domain" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "project" ADD CONSTRAINT "FK_Project_BusinessUnit"
	FOREIGN KEY ("business_unit_id") REFERENCES "business_unit" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "project" ADD CONSTRAINT "FK_Project_ProjectType"
	FOREIGN KEY ("project_type_id") REFERENCES "project_type" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "practice" ADD CONSTRAINT "FK_Practice_BusinessUnit"
	FOREIGN KEY ("business_unit_id") REFERENCES "business_unit" ("id") ON DELETE Cascade ON UPDATE Cascade
; -- change practice to bu

ALTER TABLE "group_right" ADD CONSTRAINT "FK_group_right_right"
	FOREIGN KEY ("right_id") REFERENCES "right" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "employee_status" ADD CONSTRAINT "FK_employee_status_employee"
	FOREIGN KEY ("employee_id") REFERENCES "employee" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "employee_skill" ADD CONSTRAINT "FK_employee_skill_employee"
	FOREIGN KEY ("employee_id") REFERENCES "employee" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "employee_skill" ADD CONSTRAINT "FK_employee_skill_skill_set"
	FOREIGN KEY ("skill_set_id") REFERENCES "skill_set" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "employee_project" ADD CONSTRAINT "FK_employ_project_employee"
	FOREIGN KEY ("employee_id") REFERENCES "employee" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "employee_project" ADD CONSTRAINT "FK_employ_project_project"
	FOREIGN KEY ("project_id") REFERENCES "project" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "employee_project" ADD CONSTRAINT "FK_employ_project_employee_role"
	FOREIGN KEY ("employee_role_id") REFERENCES "employee_role" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "employee_level" ADD CONSTRAINT "FK_Employee_level_Employee"
	FOREIGN KEY ("employee_id") REFERENCES "employee" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "employee_level" ADD CONSTRAINT "FK_Employee_level_level"
	FOREIGN KEY ("level_id") REFERENCES "level" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "employee_evaluation" ADD CONSTRAINT "FK_employee_evaluation_employee"
	FOREIGN KEY ("employee_id") REFERENCES "employee" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "employee_evaluation" ADD CONSTRAINT "FK_employee_evaluation_evaluation_level"
	FOREIGN KEY ("evaluation_level_id") REFERENCES "evaluation_level" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "employee" ADD CONSTRAINT "FK_employee_branch"
	FOREIGN KEY ("branch_id") REFERENCES "branch" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "employee" ADD CONSTRAINT "FK_employee_business_unit"
	FOREIGN KEY ("business_unit_id") REFERENCES "business_unit" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "employee" ADD CONSTRAINT "FK_employee_coe_core_team"
	FOREIGN KEY ("coe_core_team_id") REFERENCES "coe_core_team" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "coe_core_team" ADD CONSTRAINT "FK_coe_core_team_center_of_excellence"
	FOREIGN KEY ("coe_id") REFERENCES "center_of_excellence" ("id") ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE "business_domain" ADD CONSTRAINT "FK_BusinessDomain_Practice"
	FOREIGN KEY ("practice_id") REFERENCES "practice" ("id") ON DELETE Cascade ON UPDATE Cascade
; 

ALTER TABLE "branch" ADD CONSTRAINT "FK_branch_location"
	FOREIGN KEY ("location_id") REFERENCES "location" ("id") ON DELETE Cascade ON UPDATE Cascade
;

